# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [15]:
x=range(10,50)

y=np.array([x])
print(y)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]


4. Find the shape of previous array in question 3

In [16]:
print(y.shape)

(1, 40)


5. Print the type of the previous array in question 3

In [18]:
print(y.dtype)

int32


6. Print the numpy version and the configuration


In [21]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from 'C:\\Users\\dell\\anaconda3\\lib\\site-packages\\numpy\\version.py'>
<function show at 0x04D10610>


7. Print the dimension of the array in question 3


In [22]:
print(y.ndim)

2


8. Create a boolean array with all the True values

In [23]:
np.ones(10 , dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [27]:
np.random.rand(2,2)

array([[0.97625967, 0.90422639],
       [0.18172295, 0.50202757]])

10. Create a three dimensional array



In [28]:
np.random.rand(2,2,2)

array([[[0.34019035, 0.3016387 ],
        [0.30571118, 0.15289818]],

       [[0.05780697, 0.03715261],
        [0.98682554, 0.26205196]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [29]:
a=[2,3,4,5,6]
a[ : : -1]

[6, 5, 4, 3, 2]

12. Create a null vector of size 10 but the fifth value which is 1 

In [31]:
a=np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [34]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [38]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

arr1<arr2

array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [42]:
x=np.arange(10)
y=x[1: : 2]
print(y)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [44]:
y[::]=-1
print(y)

[-1 -1 -1 -1 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [48]:
arr = np.arange(10)
arr[4:8]=12
print(arr)

[ 0  1  2  3 12 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [62]:
y=np.ones((4,4))
y[1:-1 , 1:-1]=0
print(y)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [65]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [72]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0 , : , :]=64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [78]:
np.arange(9).reshape(3,3)[0 , 0]

0

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [79]:
np.arange(9).reshape(3,3)[1 , 1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [80]:
np.arange(9).reshape(3,3)[0:2 , 2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [84]:
y=np.random.rand(10,10)
print(y.max())
print(y.min())

0.9718298696155024
0.004023511582940342


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [87]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [93]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b ,return_indices=True)

(array([2, 4]), array([1, 5], dtype=int32), array([1, 5], dtype=int32))

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Will"]


array([[-0.51360545, -0.66625891, -1.18716032, -0.26506641],
       [ 1.18890274, -0.37994134,  0.32325   ,  0.3439915 ],
       [ 2.30008681, -1.20385597, -0.16419999, -0.62192214],
       [-0.6062944 ,  0.590731  ,  0.84400165,  0.2458862 ],
       [ 1.28244096, -1.02763395, -0.07557175, -0.2641702 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
both = (names != "Will") | (names != "Joe")
data[both]

array([[ 0.23174978, -2.89408728, -0.10376123,  0.08339167],
       [ 0.06602984,  0.53918868, -1.24786266,  0.3713499 ],
       [ 0.45490817,  0.18505187, -1.20188434, -0.46078311],
       [-0.33747017,  0.57563381, -0.36747918, -0.9785141 ],
       [ 0.59221341, -0.71880702,  0.69197769, -1.23591833],
       [-1.13904025,  1.37956241, -0.16364309, -1.25084264],
       [-0.82709451,  0.2181597 ,  0.17326563,  0.74804384]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [104]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [106]:
z=np.arange(1,17).reshape(2,2,4)
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [115]:
np.swapaxes(z, 1 , 0)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [122]:
y=np.arange(10)
t=np.sqrt(y)
t[t<0.5]=0
t

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [130]:
q=np.random.rand(12)
u=np.random.rand(12)
np.maximum(q,u)

array([0.51176658, 0.35326175, 0.9464633 , 0.27519713, 0.63373713,
       0.56983874, 0.85542696, 0.31839666, 0.45058927, 0.19186703,
       0.5346402 , 0.63632583])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [131]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [138]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [145]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])

sampleArray[1]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [146]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [148]:
np.random.rand(20).sum()

12.12975824528819